# fly.toml app configuration file generated for tasklist-rough-sea-7423 on 2025-02-28T11:05:19+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tasklist-rough-sea-7423'
primary_region = 'nrt'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'
  APP_NAME = 'laravel'
  APP_URL = 'https://tasklist-rough-sea-7423.fly.dev'
  DATABASE_URL = 'postgresql://postgres.ybvodriwqqojwouejidv:j9CQqHJDEUICLCTj@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres'
  DB_CONNECTION = 'pgsql'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'